# Persistent Volume Claim
#Данный тип ресурса позволяет хранить персистентные данные ваших приложений. Для того, чтобы использовать PVC, Вам необходимо, чтобы в кластере был реализован интерфейс CSI (Container Storage Interface) администратором кластера. PVC своего рода запрос необходимого постоянного тома (диска). Вам, как пользователю, не обязательно знать какой это будет диск и откуда, нужно лишь указать сколько дискового пространства Вам необходимо для использования. После размещения PVC в кластере, будет создан автоматически ресурс PV (Persistent Volume), который ссылается на конкретный физический том, и будет налажена связь между данными PVC и PV. В некоторых кластерах за создание PV отвечает администратор, как на картинке ниже, однако в последнее время все чаще этим администратором является драйвер, который делает все автоматически.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "default"  # default используется по умолчанию, можно прописать тот класс,
  resources:                   # который сообщит Вам администратор
    requests:
      storage: 30Gi

#Остается примонтировать наш PVC к нашему Поду:
#
#spec:
#  containers:
#    - name: web
#      image: ksxack/lesson1:v0.2
#      ports:
#        - containerPort: 8080
#      volumeMounts:
#      - mountPath: "/data"
#        name: my-volume
#  volumes:
#    - name: my-volume
#      persistentVolumeClaim:
#        claimName: my-pvc
